version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379" # Porta padrão do Redis
    volumes:
      - redis-data:/data # Volume para persistir os dados
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
